// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:buff_lisa/data/entity/group_entity.dart';
import 'package:buff_lisa/data/entity/image_entity.dart';
import 'package:buff_lisa/data/entity/member_entity.dart';
import 'package:buff_lisa/data/entity/pin_entity.dart';
import 'package:buff_lisa/data/entity/pin_like_entity.dart';
import 'package:buff_lisa/data/entity/season_entity.dart';
import 'package:buff_lisa/data/entity/user_entity.dart';
import 'package:buff_lisa/data/entity/user_like_entity.dart';
import 'package:buff_lisa/data/entity/user_pins_entity.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(GroupEntityAdapter());
    registerAdapter(ImageEntityAdapter());
    registerAdapter(MemberEntityAdapter());
    registerAdapter(MembersEntityAdapter());
    registerAdapter(PinEntityAdapter());
    registerAdapter(PinLikeEntityAdapter());
    registerAdapter(SeasonEntityAdapter());
    registerAdapter(UserEntityAdapter());
    registerAdapter(UserLikeEntityAdapter());
    registerAdapter(UserPinsEntityAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(GroupEntityAdapter());
    registerAdapter(ImageEntityAdapter());
    registerAdapter(MemberEntityAdapter());
    registerAdapter(MembersEntityAdapter());
    registerAdapter(PinEntityAdapter());
    registerAdapter(PinLikeEntityAdapter());
    registerAdapter(SeasonEntityAdapter());
    registerAdapter(UserEntityAdapter());
    registerAdapter(UserLikeEntityAdapter());
    registerAdapter(UserPinsEntityAdapter());
  }
}
