name: Build and test flutter

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - name: Clone repository
      uses: actions/checkout@v4
    - name: Create .env files
      run: |
        touch .env
        touch .env.dev
        echo "API_HOST=${{ secrets.API_HOST }}" > .env
        echo "MINIO_HOST=${{ secrets.MINIO_HOST }}" >> .env
        echo "DISCORD_INVITE=${{ secrets.DISCORD_INVITE }}" >> .env
        echo "INSTAGRAM_URL=${{ secrets.INSTAGRAM_URL }}" >> .env
        echo "GITHUB_URL=${{ secrets.GITHUB_URL }}" >> .env
        echo "APPSTORE_ID=${{ secrets.APPSTORE_ID }}" >> .env
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: any
        flutter-version: 3.x
    - name: Install dependencies
      run: |
        flutter --version
        flutter pub get

    - name: Lint code
      id: lint
      run: |
        flutter analyze > analysis_results.txt || true
        echo "::set-output name=results::$(cat analysis_results.txt)"

    - name: Format analysis results
      run: |
        echo "### Flutter Analyze Results" > formatted_results.txt
        cat analysis_results.txt | sed 's/^info • /- [ ] /' >> formatted_results.txt
        echo "" >> formatted_results.txt
        echo "### Flutter Analyze Results" >> formatted_results.txt
        cat formatted_results.txt

    - uses: mshick/add-pr-comment@v2
      with:
        message-id: "flutter_analyze"
        message-path: formatted_results.txt

    - name: Run tests
      run: flutter test

    - name: Build APK
      run: flutter build apk --debug
