name: Build and test flutter

on:
  push: # Runs on every push to any branch

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      packages: write 

    steps:
    - name: Clone repository
      uses: actions/checkout@v4

    - name: Add google services
      run: |
        touch ./android/app/google-services.json
        echo "${{ secrets.GOOGLE_SERVICES }}" | base64 -d > ./android/app/google-services.json

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        flutter-version: 3.x

    - name: Install dependencies
      run: |
        flutter --version
        flutter pub get

    - name: Lint code
      id: lint
      run: |
        flutter analyze > analysis_results.txt || true
        echo "::set-output name=results::$(cat analysis_results.txt)"

    - name: Format analysis results
      run: |
        echo "### Flutter Analyze Results" > formatted_results.txt
        cat analysis_results.txt | sed 's/^   info • /- [ ] /' >> formatted_results.txt
        cat formatted_results.txt

    - uses: mshick/add-pr-comment@v2
      with:
        message-id: "flutter_analyze"
        message-path: formatted_results.txt

    - name: Build APK
      run: flutter build apk --debug

    # --- STEPS RESTRICTED TO MAIN BRANCH ONLY ---

    - name: Log in to GitHub Container Registry
      if: github.ref == 'refs/heads/main'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      if: github.ref == 'refs/heads/main'
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository }}

    - name: Build and push Docker image
      if: github.ref == 'refs/heads/main'
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}